name: cortex

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cortex
      POSTGRES_PASSWORD: cortex
      POSTGRES_DB: cortex
    healthcheck: { test: ["CMD-SHELL", "pg_isready -U cortex"], interval: 5s, timeout: 5s, retries: 10 }
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Expose to localhost for gateway (host network mode) to connect
    ports:
      - "127.0.0.1:${CORTEX_POSTGRES_PORT:-15432}:5432"

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    # Expose to localhost for gateway (host network mode) to connect
    ports:
      - "127.0.0.1:${CORTEX_REDIS_PORT:-16379}:6379"

  gateway:
    image: your-registry/cortex-gateway:latest
    # =========================================================================
    # HOST NETWORK MODE - Universal External Access
    # =========================================================================
    # Using host network mode allows ANY Docker container or external application
    # to reach the Cortex API at http://<HOST_IP>:8084 or http://host.docker.internal:8084
    # without requiring manual network configuration.
    # =========================================================================
    network_mode: host
    env_file:
      - ./backend/.env.prod
    environment:
      VLLM_GEN_URLS: ""
      VLLM_EMB_URLS: ""
      INTERNAL_VLLM_API_KEY: ${INTERNAL_VLLM_API_KEY}
      GATEWAY_DEV_ALLOW_ALL_KEYS: "false"
      CORTEX_MODELS_DIR: ${CORTEX_MODELS_DIR:-/var/cortex/models}
      HF_CACHE_DIR: ${HF_CACHE_DIR:-/var/cortex/hf-cache}
      # Keep in sync with backend/src/config.py and scripts/prepare-offline-deployment.sh
      # NOTE: Qwen3 requires newer Transformers, so default to a compatible image.
      VLLM_IMAGE: ${VLLM_IMAGE:-vllm/vllm-openai:latest}
      # Database and Redis URLs - use localhost since gateway is on host network
      DATABASE_URL: postgresql+asyncpg://cortex:cortex@127.0.0.1:${CORTEX_POSTGRES_PORT:-15432}/cortex
      REDIS_URL: redis://127.0.0.1:${CORTEX_REDIS_PORT:-16379}/0
    # Note: 'ports' is not used with network_mode: host - gateway listens on host port 8084 directly
    depends_on: [redis, postgres]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CORTEX_MODELS_DIR:-/var/cortex/models}:/var/cortex/models:ro
      - ${HF_CACHE_DIR:-/var/cortex/hf-cache}:/var/cortex/hf-cache
      # Persist Deployment exports (manifests/images/db dumps) on host
      - ${CORTEX_EXPORT_DIR:-/var/cortex/exports}:/var/cortex/exports

volumes:
  postgres_data:
  redis_data: