"""baseline: schema as created by create_all before Alembic (Cortex 0.1.1)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-02
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(128), nullable=False, unique=True, index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("org_id", sa.Integer(), sa.ForeignKey("organizations.id"), nullable=True),
        sa.Column("username", sa.String(255), nullable=False, unique=True, index=True),
        sa.Column("role", sa.String(32), nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("org_id", sa.Integer(), sa.ForeignKey("organizations.id"), nullable=True),
        sa.Column("prefix", sa.String(16), nullable=False, unique=True, index=True),
        sa.Column("hash", sa.String(256), nullable=False),
        sa.Column("scopes", sa.String(128), nullable=False),
        sa.Column("ip_allowlist", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=False)
    )
    op.create_table(
        "usage",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("org_id", sa.Integer(), sa.ForeignKey("organizations.id"), nullable=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("key_id", sa.Integer(), sa.ForeignKey("api_keys.id"), nullable=True),
        sa.Column("model_name", sa.String(255), nullable=False),
        sa.Column("task", sa.String(32), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("req_id", sa.String(64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("served_model_name", sa.String(255), nullable=False),
        sa.Column("repo_id", sa.String(512), nullable=True),
        sa.Column("local_path", sa.String(512), nullable=True),
        sa.Column("task", sa.String(32), nullable=False),
        sa.Column("dtype", sa.String(32), nullable=True),
        sa.Column("tp_size", sa.Integer(), nullable=True),
        sa.Column("gpu_memory_utilization", sa.Float(), nullable=True),
        sa.Column("max_model_len", sa.Integer(), nullable=True),
        sa.Column("kv_cache_dtype", sa.String(32), nullable=True),
        sa.Column("max_num_batched_tokens", sa.Integer(), nullable=True),
        sa.Column("quantization", sa.String(64), nullable=True),
        sa.Column("block_size", sa.Integer(), nullable=True),
        sa.Column("swap_space_gb", sa.Integer(), nullable=True),
        sa.Column("enforce_eager", sa.Boolean(), nullable=True),
        sa.Column("trust_remote_code", sa.Boolean(), nullable=True),
        sa.Column("cpu_offload_gb", sa.Integer(), nullable=True),
        sa.Column("enable_prefix_caching", sa.Boolean(), nullable=True),
        sa.Column("prefix_caching_hash_algo", sa.String(32), nullable=True),
        sa.Column("enable_chunked_prefill", sa.Boolean(), nullable=True),
        sa.Column("max_num_seqs", sa.Integer(), nullable=True),
        sa.Column("cuda_graph_sizes", sa.Text(), nullable=True),
        sa.Column("pipeline_parallel_size", sa.Integer(), nullable=True),
        sa.Column("device", sa.String(16), nullable=True),
        sa.Column("tokenizer", sa.String(255), nullable=True),
        sa.Column("hf_config_path", sa.String(512), nullable=True),
        sa.Column("hf_token", sa.Text(), nullable=True),
        sa.Column("engine_type", sa.String(16), nullable=False),
        sa.Column("engine_image", sa.String(256), nullable=True),
        sa.Column("engine_version", sa.String(32), nullable=True),
        sa.Column("engine_digest", sa.String(128), nullable=True),
        sa.Column("selected_gpus", sa.Text(), nullable=True),
        sa.Column("ngl", sa.Integer(), nullable=True),
        sa.Column("tensor_split", sa.String(128), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("ubatch_size", sa.Integer(), nullable=True),
        sa.Column("threads", sa.Integer(), nullable=True),
        sa.Column("context_size", sa.Integer(), nullable=True),
        sa.Column("parallel_slots", sa.Integer(), nullable=True),
        sa.Column("rope_freq_base", sa.Float(), nullable=True),
        sa.Column("rope_freq_scale", sa.Float(), nullable=True),
        sa.Column("flash_attention", sa.Boolean(), nullable=True),
        sa.Column("mlock", sa.Boolean(), nullable=True),
        sa.Column("no_mmap", sa.Boolean(), nullable=True),
        sa.Column("numa_policy", sa.String(32), nullable=True),
        sa.Column("split_mode", sa.String(32), nullable=True),
        sa.Column("cache_type_k", sa.String(16), nullable=True),
        sa.Column("cache_type_v", sa.String(16), nullable=True),
        sa.Column("attention_backend", sa.String(32), nullable=True),
        sa.Column("disable_log_requests", sa.Boolean(), nullable=True),
        sa.Column("disable_log_stats", sa.Boolean(), nullable=True),
        sa.Column("vllm_v1_enabled", sa.Boolean(), nullable=True),
        sa.Column("gguf_weight_format", sa.String(16), nullable=True),
        sa.Column("entrypoint_override", sa.String(256), nullable=True),
        sa.Column("debug_logging", sa.Boolean(), nullable=True),
        sa.Column("trace_mode", sa.Boolean(), nullable=True),
        sa.Column("engine_request_timeout", sa.Integer(), nullable=True),
        sa.Column("max_log_len", sa.Integer(), nullable=True),
        sa.Column("repetition_penalty", sa.Float(), nullable=True),
        sa.Column("frequency_penalty", sa.Float(), nullable=True),
        sa.Column("presence_penalty", sa.Float(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("top_k", sa.Integer(), nullable=True),
        sa.Column("top_p", sa.Float(), nullable=True),
        sa.Column("request_defaults_json", sa.Text(), nullable=True),
        sa.Column("request_timeout_sec", sa.Integer(), nullable=True),
        sa.Column("stream_timeout_sec", sa.Integer(), nullable=True),
        sa.Column("engine_startup_args_json", sa.Text(), nullable=True),
        sa.Column("engine_startup_env_json", sa.Text(), nullable=True),
        sa.Column("draft_model_path", sa.String(512), nullable=True),
        sa.Column("draft_n", sa.Integer(), nullable=True),
        sa.Column("draft_p_min", sa.Float(), nullable=True),
        sa.Column("startup_timeout_sec", sa.Integer(), nullable=True),
        sa.Column("verbose_logging", sa.Boolean(), nullable=True),
        sa.Column("check_tensors", sa.Boolean(), nullable=True),
        sa.Column("skip_warmup", sa.Boolean(), nullable=True),
        sa.Column("chat_template", sa.Text(), nullable=True),
        sa.Column("chat_template_file", sa.String(512), nullable=True),
        sa.Column("jinja_enabled", sa.Boolean(), nullable=True),
        sa.Column("defrag_thold", sa.Float(), nullable=True),
        sa.Column("lora_adapters_json", sa.Text(), nullable=True),
        sa.Column("lora_init_without_apply", sa.Boolean(), nullable=True),
        sa.Column("grammar_file", sa.String(512), nullable=True),
        sa.Column("enable_embeddings", sa.Boolean(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("cont_batching", sa.Boolean(), nullable=True),
        sa.Column("state", sa.String(16), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("container_name", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("model_id", sa.Integer(), sa.ForeignKey("models.id"), nullable=True),
        sa.Column("model_name", sa.String(255), nullable=False),
        sa.Column("served_model_name", sa.String(255), nullable=False),
        sa.Column("task", sa.String(32), nullable=False),
        sa.Column("engine_type", sa.String(16), nullable=False),
        sa.Column("engine_image", sa.String(256), nullable=True),
        sa.Column("engine_version", sa.String(32), nullable=True),
        sa.Column("engine_digest", sa.String(128), nullable=True),
        sa.Column("selected_gpus", sa.Text(), nullable=True),
        sa.Column("mode", sa.String(16), nullable=False),
        sa.Column("repo_id", sa.String(512), nullable=True),
        sa.Column("local_path", sa.String(512), nullable=True),
        sa.Column("dtype", sa.String(32), nullable=True),
        sa.Column("tp_size", sa.Integer(), nullable=True),
        sa.Column("gpu_memory_utilization", sa.Float(), nullable=True),
        sa.Column("max_model_len", sa.Integer(), nullable=True),
        sa.Column("kv_cache_dtype", sa.String(32), nullable=True),
        sa.Column("max_num_batched_tokens", sa.Integer(), nullable=True),
        sa.Column("quantization", sa.String(64), nullable=True),
        sa.Column("block_size", sa.Integer(), nullable=True),
        sa.Column("swap_space_gb", sa.Integer(), nullable=True),
        sa.Column("enforce_eager", sa.Boolean(), nullable=True),
        sa.Column("trust_remote_code", sa.Boolean(), nullable=True),
        sa.Column("cpu_offload_gb", sa.Integer(), nullable=True),
        sa.Column("enable_prefix_caching", sa.Boolean(), nullable=True),
        sa.Column("prefix_caching_hash_algo", sa.String(32), nullable=True),
        sa.Column("enable_chunked_prefill", sa.Boolean(), nullable=True),
        sa.Column("max_num_seqs", sa.Integer(), nullable=True),
        sa.Column("cuda_graph_sizes", sa.Text(), nullable=True),
        sa.Column("pipeline_parallel_size", sa.Integer(), nullable=True),
        sa.Column("device", sa.String(16), nullable=True),
        sa.Column("tokenizer", sa.String(255), nullable=True),
        sa.Column("hf_config_path", sa.String(512), nullable=True),
        sa.Column("hf_token", sa.Text(), nullable=True),
        sa.Column("ngl", sa.Integer(), nullable=True),
        sa.Column("tensor_split", sa.String(128), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("ubatch_size", sa.Integer(), nullable=True),
        sa.Column("threads", sa.Integer(), nullable=True),
        sa.Column("context_size", sa.Integer(), nullable=True),
        sa.Column("parallel_slots", sa.Integer(), nullable=True),
        sa.Column("rope_freq_base", sa.Float(), nullable=True),
        sa.Column("rope_freq_scale", sa.Float(), nullable=True),
        sa.Column("flash_attention", sa.Boolean(), nullable=True),
        sa.Column("mlock", sa.Boolean(), nullable=True),
        sa.Column("no_mmap", sa.Boolean(), nullable=True),
        sa.Column("numa_policy", sa.String(32), nullable=True),
        sa.Column("split_mode", sa.String(32), nullable=True),
        sa.Column("cache_type_k", sa.String(16), nullable=True),
        sa.Column("cache_type_v", sa.String(16), nullable=True),
        sa.Column("attention_backend", sa.String(32), nullable=True),
        sa.Column("disable_log_requests", sa.Boolean(), nullable=True),
        sa.Column("disable_log_stats", sa.Boolean(), nullable=True),
        sa.Column("vllm_v1_enabled", sa.Boolean(), nullable=True),
        sa.Column("entrypoint_override", sa.String(256), nullable=True),
        sa.Column("debug_logging", sa.Boolean(), nullable=True),
        sa.Column("trace_mode", sa.Boolean(), nullable=True),
        sa.Column("engine_request_timeout", sa.Integer(), nullable=True),
        sa.Column("max_log_len", sa.Integer(), nullable=True),
        sa.Column("repetition_penalty", sa.Float(), nullable=True),
        sa.Column("frequency_penalty", sa.Float(), nullable=True),
        sa.Column("presence_penalty", sa.Float(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("top_k", sa.Integer(), nullable=True),
        sa.Column("top_p", sa.Float(), nullable=True),
        sa.Column("request_defaults_json", sa.Text(), nullable=True),
        sa.Column("request_timeout_sec", sa.Integer(), nullable=True),
        sa.Column("stream_timeout_sec", sa.Integer(), nullable=True),
        sa.Column("engine_startup_args_json", sa.Text(), nullable=True),
        sa.Column("engine_startup_env_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_table(
        "config_kv",
        sa.Column("key", sa.String(128), primary_key=True, nullable=False),
        sa.Column("value", sa.Text(), nullable=False)
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(64), primary_key=True, nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False, index=True),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("model_name", sa.String(255), nullable=False),
        sa.Column("engine_type", sa.String(32), nullable=False),
        sa.Column("constraints_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("session_id", sa.String(64), sa.ForeignKey("chat_sessions.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )

def downgrade() -> None:
    for t in ("chat_messages", "chat_sessions", "config_kv", "recipes", "models", "usage", "users", "organizations", "api_keys"):
        op.drop_table(t)
